version: '2'
services:
  c-tet-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ../tet/static:/usr/share/nginx/html/static
    networks:
      - nginx-load-balancer
      - tet
  c-tet-app:
    build:
      context: ..
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ..:/opt/tet
    networks:
      - tet
networks:
  tet:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
